#!/system/etc/CrossBreeder/busybox sh

set +e

# These are based on Thunderbolt values modified for use with CrossBreeder

#Credits to Thunderbolt team
# zacharias.maladroit
# voku1987
# collin_ph@xda

alias [='busybox ['
alias [[='busybox [['


GOVERNOR=`cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor`
if [ "$GOVERNOR" = "smartassV2" ]; then
   GOVERNOR="smartass"
fi

SET_VALUE() {
  if [ -e $2 ]; then
    VALUE=`cat $2 2>/dev/null`
    if [ "x$VALUE" != "x$1" ]; then
      echo $1 > $2
    fi
  fi
}

for i in "" "cpu0" "cpu1" "cpu2" "cpu3" "cpu4" "cpu5" "cpu6" "cpu7" "cpu8" "cpu9" "cpu10" "cpu11" "cpu12" "cpu13" "cpu14" "cpu15"; do
DIRECTORY="/sys/devices/system/cpu/${i}/cpufreq/$GOVERNOR"

if [ -e $DIRECTORY/sampling_rate ]; then 
  SAMPLING_RATE=`cat $DIRECTORY/sampling_rate`
  if [ "$SAMPLING_RATE" -gt 100000 ]; then 
    SET_VALUE "100000" $DIRECTORY/sampling_rate
  fi
  if [ "$SAMPLING_RATE" -lt 40000 ]; then 
    SET_VALUE "40000" $DIRECTORY/sampling_rate
  fi
fi

if [ -e $DIRECTORY/timer_rate ]; then
  SAMPLING_RATE=`cat $DIRECTORY/timer_rate`
  if [ "$SAMPLING_RATE" -gt 100000 ]; then
    SET_VALUE "100000" $DIRECTORY/timer_rate
  fi
  if [ "$SAMPLING_RATE" -lt 40000 ]; then
    SET_VALUE "40000" $DIRECTORY/timer_rate
  fi
fi

if [ "$GOVERNOR" = "interactive" ]; then
        SET_VALUE "85" $DIRECTORY/go_maxspeed_load
        SET_VALUE "85" $DIRECTORY/go_hispeed_load
        SET_VALUE "10000" $DIRECTORY/min_sample_time
        SET_VALUE "40000" $DIRECTORY/timer_rate
elif [ "$GOVERNOR" = "ondemand" ]; then
        SET_VALUE "85" $DIRECTORY/up_threshold
        SET_VALUE "2" $DIRECTORY/powersave_bias
        SET_VALUE "10" $DIRECTORY/down_differential
        SET_VALUE "1" $DIRECTORY/sampling_down_factor
        SET_VALUE "1" $DIRECTORY/io_is_busy
        SET_VALUE "0" $DIRECTORY/ignore_nice_load
        SET_VALUE "100000" $DIRECTORY/sampling_rate
        SET_VALUE "40000" $DIRECTORY/sampling_rate
elif [ "$GOVERNOR" = "ondemandx" ]; then
        SET_VALUE "85" $DIRECTORY/up_threshold
        SET_VALUE "50" $DIRECTORY/powersave_bias
        SET_VALUE "10" $DIRECTORY/down_differential
        SET_VALUE "1" $DIRECTORY/sampling_down_factor
        SET_VALUE "0" $DIRECTORY/ignore_nice_load
        SET_VALUE "100000" $DIRECTORY/sampling_rate
        SET_VALUE "40000" $DIRECTORY/sampling_rate                                    
elif [ "$GOVERNOR" = "conservative" ]; then
        SET_VALUE "85" $DIRECTORY/up_threshold
	SET_VALUE "75" $DIRECTORY/down_threshold
        SET_VALUE "100" $DIRECTORY/freq_step
elif [ "$GOVERNOR" = "lulzactive" ]; then
	SET_VALUE "85" $DIRECTORY/inc_cpu_load
	SET_VALUE "1" $DIRECTORY/pump_down_step
elif [ "$GOVERNOR" = "smartass" ]; then
	SET_VALUE "500000" $DIRECTORY/awake_ideal_freq
	CAT /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq > $DIRECTORY/sleep_ideal_freq
	SET_VALUE "800000" $DIRECTORY/sleep_wakeup_freq
	SET_VALUE "85" $DIRECTORY/max_cpu_load
	SET_VALUE "75" $DIRECTORY/min_cpu_load
	SET_VALUE "200000" $DIRECTORY/ramp_down_step
	SET_VALUE "0" $DIRECTORY/ramp_up_step
elif [ "$GOVERNOR" = "abyssplug" ]; then
	SET_VALUE "85" $DIRECTORY/up_threshold
	SET_VALUE "40" $DIRECTORY/down_threshold
	SET_VALUE "5" $DIRECTORY/hotplug_in_sampling_periods
	SET_VALUE "20" $DIRECTORY/hotplug_out_sampling_periods
	SET_VALUE "10" $DIRECTORY/down_differential
	SET_VALUE "40000" $DIRECTORY/sampling_rate
elif [ "$GOVERNOR" = "pegasusq" ]; then
	SET_VALUE "85" $DIRECTORY/up_threshold
	SET_VALUE "10" $DIRECTORY/down_differential
	SET_VALUE "1" $DIRECTORY/sampling_down_factor
	SET_VALUE "40000" $DIRECTORY/sampling_rate
	SET_VALUE "100" $DIRECTORY/freq_step
	SET_VALUE "5" $DIRECTORY/cpu_up_rate
	SET_VALUE "20" $DIRECTORY/cpu_down_rate
	SET_VALUE "100000" $DIRECTORY/freq_for_responsiveness
elif [ "$GOVERNOR" = "hotplug" ]; then
	SET_VALUE "85" $DIRECTORY/up_threshold
	SET_VALUE "40" $DIRECTORY/down_threshold
	SET_VALUE "5" $DIRECTORY/hotplug_in_sampling_periods
	SET_VALUE "20" $DIRECTORY/hotplug_out_sampling_periods
	SET_VALUE "10" $DIRECTORY/down_differential
	SET_VALUE "40000" $DIRECTORY/sampling_rate
fi


done