#!/system/bin/sh

set +e

( busybox kill -9 $(busybox pgrep -f "dnsmasq_dhcp --no-daemon \-port=10053"); busybox kill -9 $(busybox pgrep -f dnsmasq) ) &

exec 1>/data/DNSMasq.log 2>&1

( dnsmasq_dhcp --no-daemon --port=10053 --dhcp-option=252 --no-ping --dhcp-authoritative $* )&
pid=$!
wait $pid

echo "Run dnsmasq_dhcp failed, try dnsmasq..."

( dnsmasq --no-daemon --port=10053 $* )&
pid=$!
wait $pid
