#!/system/bin/sh

XRANDOM="$(busybox cat /data/CrossBreeder/zzCrossBreeder/RANDOM)"
HAVEGED="$(busybox cat /data/CrossBreeder/zzCrossBreeder/HAVEGED)"
PUNCHMOD="$(busybox cat /data/CrossBreeder/zzCrossBreeder/PUNCHMOD)"

if [ "$XRANDOM" = "1" ]; then

RANDOMDEVICE=urandom
if [ -c /dev/erandom ]; then
  if [ ! -f /dev/urandom.MOD ]; then
    touch /dev/urandom.MOD
    busybox mv /dev/urandom /dev/urandom.ORIG
    busybox ln /dev/erandom /dev/urandom
    sleep 2
  fi
  busybox chmod 666 /dev/frandom
  busybox chmod 666 /dev/erandom
  RANDOMDEVICE=frandom
fi

if [ "$PUNCHMOD" = "1" ]; then

if [ ! -c /dev/erandom ]; then
  punchmod /system/lib/modules/frandom.ko "" "" 2>/dev/null
fi

fi

URANDOMDEVICE="/dev/urandom"
if [ -c /dev/erandom ]; then
  if [ ! -f /dev/urandom.MOD ]; then 
    touch /dev/urandom.MOD
    busybox mv /dev/urandom /dev/urandom.ORIG
    busybox ln /dev/erandom /dev/urandom
    sleep 2
  fi
  busybox chmod 666 /dev/frandom
  busybox chmod 666 /dev/erandom
  RANDOMDEVICE=frandom
  if [ ! -c /dev/urandom.ORIG ]; then 
    busybox mknod -m 666 /dev/urandom.ORIG c 1 9
    sleep 2
  fi
  URANDOMDEVICE="/dev/urandom.ORIG"
elif [ ! -c /dev/urandom ]; then
  busybox mknod -m 666 /dev/urandom c 1 9
  sleep 2
fi

if [ ! -f /dev/random.MOD ]; then  
  touch /dev/random.MOD
  busybox rm /dev/random
  busybox ln /dev/$RANDOMDEVICE /dev/random
  sleep 2
fi

setprop ro.wmt.blcr.enable 0

for i in `busybox find /sys -name add_random -print 2>/dev/null`; do busybox echo 0 > $i; done

fi

if [ "$HAVEGED" = "1" ] && [ "$XRANDOM" = "1" ]; then

( haveged --Foreground --sink=$URANDOMDEVICE --write=0 --pidfile=/data/haveged.pid )&

busybox sysctl -w kernel.random.read_wakeup_threshold=8;
busybox sysctl -w kernel.random.write_wakeup_threshold=0;

sys_pid=`busybox pgrep system_server 2>/dev/null`

busybox renice -10 $sys_pid 2>/dev/null

for i in $(busybox pgrep haveged 2>/dev/null); do 
  busybox renice +20 $i 2>/dev/null
done

touch /dev/CB_RunHaveged.RUN

fi
