#!/system/bin/sh

ALL="$(busybox cat /data/CrossBreeder/dynbsd/ALL)"
CORES=$(grep -c 'processor' /proc/cpuinfo);
CONF1="$(busybox cat /data/CrossBreeder/dynbsd/CONF1)"
CONF2="$(busybox cat /data/CrossBreeder/dynbsd/CONF2)"
CONF3="$(busybox cat /data/CrossBreeder/dynbsd/CONF3)"
CONF4="$(busybox cat /data/CrossBreeder/dynbsd/CONF4)"

if [ "$ALL" = "1" ];then

if [ "$CORES" -ge "4" ];then
  ( dynbsd start -h $CONF1 -ns $CONF2 -d $CONF3 -lt $CONF4 )&
fi

exit 0

fi
