#!/system/bin/sh

ALL="$(busybox cat /data/CrossBreeder/dynlmk/ALL)"
CONF="$(busybox cat /data/CrossBreeder/dynlmk/CONF)"
TURN=$(( $CONF+5 ))

if [ "$ALL" = "1" ]; then

#calculate values
RAM=$((`busybox awk '/MemTotal/{print $2}' /proc/meminfo`))
sval1=$(($(busybox awk '/SwapFree/{print $2}' /proc/meminfo) ))
FREEMEM=$((`busybox awk '/MemFree/{print $2}' /proc/meminfo` + $sval1 ))

for mem in ${!FREEMEM[@]}
do
setmem=$(( $setmem+${FREEMEM[$mem]} ))
done
setmem=$(($setmem/${#FREEMEM[@]}))
busybox echo "Average memory usage: $setmem"
ADDMEM=$((setmem * $TURN / 10))

VAL1=$(( ( ( $RAM* 1 / 1000 ) + ( $ADDMEM / 12 ) ) / 4 ))
VAL2=$(( ( ( $RAM* 3 / 1000 ) + ( $ADDMEM / 7 ) ) / 4 ))
VAL3=$(( ( ( $RAM* 6 / 1000 ) + ( $ADDMEM / 5 ) ) / 4 ))
VAL4=$(( ( ( $RAM* 10 / 1000 ) + ( $ADDMEM / 4 ) ) / 4 ))
VAL5=$(( ( ( $RAM* 13 / 1000 ) + ( $ADDMEM / 3 ) ) / 4 ))
VAL6=$(( ( ( $RAM* 18 / 1000 ) + ( $ADDMEM / 2 ) ) / 4 ))

busybox echo "Detected you have $(($RAM / 1024)) megabytes of system RAM."

busybox echo "Now set your LMK parameters."

busybox echo "=> Current setup:"
busybox echo "=> $(($VAL1 * 4 / 1024 )) MB for Foreground Applications"
busybox echo "=> $(($VAL2 * 4 / 1024 )) MB for Visible Applications"
busybox echo "=> $(($VAL3 * 4 / 1024 )) MB for Secondary Server"
busybox echo "=> $(($VAL4 * 4 / 1024 )) MB for Hidden Applications"
busybox echo "=> $(($VAL5 * 4 / 1024 )) MB for Content Provider"
busybox echo "=> $(($VAL6 * 4 / 1024 )) MB for Empty Applications"

#set lmk
LMK=/sys/module/lowmemorykiller/parameters/minfree

busybox echo "$VAL1,$VAL2,$VAL3,$VAL4,$VAL5,$VAL6" > $LMK

#log everything
LMK=$(busybox cat "/sys/module/lowmemorykiller/parameters/minfree")

if [ "${LMK}" == "${VAL1},${VAL2},${VAL3},${VAL4},${VAL5},${VAL6}" ]; then
busybox echo "LMK parameters set."
else 
busybox echo "Failed setting LMK parameters."
fi

busybox echo "Now monitor your system to set intelligently LMK parameters for you."

fi
