#!/system/bin/sh
#ThunderBolt!
#Credit to pikachu01
#Smart Mounting by ImbaWind
#Adrenaline Engine Specified

export PATH=/system/etc/CrossBreeder:$PATH:/sbin:/vendor/bin:/system/sbin:/system/bin:/system/xbin:

ENABLE="$(busybox cat /data/CrossBreeder/EXT4_LAGFIX/ENABLE)"
TUNE2FS="$(busybox cat /data/CrossBreeder/EXT4_LAGFIX/TUNE2FS)"

if [ "$ENABLE" = "1" ]; then

if ( mount | grep -w ext4 ) then
	echo "EXT4 Partition Found!" >> /data/EXT4_LAGFIX.log
	echo "Remounting..." >> /data/EXT4_LAGFIX.log 
	echo "" >> /data/EXT4_LAGFIX.log
	mount -o noatime,remount,rw,discard,barrier=0,commit=60,noauto_da_alloc >> /data/EXT4_LAGFIX.log
	mount -o noatime,remount,rw,discard,barrier=0,commit=60,noauto_da_alloc >> /data/EXT4_LAGFIX.log
else
	echo "EXT4 Partition Not Found!" >> /data/EXT4_LAGFIX.log
fi;

fi

exec 1>/data/TUNE2FS.log 2>&1

if [ "$TUNE2FS" = "1" ]; then

for m in $(busybox mount | busybox awk '{ if ($5 ~ /^ext/) print $1,$3 }' | busybox grep "/data" | busybox awk '{ print $1 }');
do
  tune2fs -f -o journal_data_writeback $m 2>/dev/null
  tune2fs -f -O dir_index $m 2>/dev/null  
  busybox hdparm -S 4 $m 2>/dev/null
done;

for m in $(busybox mount | busybox awk '{ if ($5 ~ /^ext/) print $1,$3 }' | busybox grep "/system" | busybox awk '{ print $1 }');
do
  tune2fs -f -o journal_data_writeback $m 2>/dev/null
  debugfs -w -R "feature ^needs_recovery" $m 2>/dev/null
  tune2fs -f -O ^needs_recovery $m 2>/dev/null
  tune2fs -f -O ^has_journal $m 2>/dev/null
  tune2fs -f -O dir_index $m 2>/dev/null
  busybox hdparm -r $m 2>/dev/null
done;

fi
