#!/system/bin/sh
#ThunderBolt!
#Credit to pikachu01
#Smart Mounting by ImbaWind
#Adrenaline Engine Specified

ENABLE="$(busybox cat /data/CrossBreeder/EXT4_LAGFIX/ENABLE)"

if [ "$ENABLE" = "1" ]; then

if ( mount | grep -w ext4 ) then
	echo "EXT4 Partition Found!" >> /data/EXT4_LAGFIX.log
	echo "Remounting..." >> /data/EXT4_LAGFIX.log 
	echo "" >> /data/EXT4_LAGFIX.log
	mount -o noatime,remount,rw,discard,barrier=0,commit=60,noauto_da_alloc >> /data/EXT4_LAGFIX.log
	mount -o noatime,remount,rw,discard,barrier=0,commit=60,noauto_da_alloc >> /data/EXT4_LAGFIX.log
else
	echo "EXT4 Partition Not Found!" >> /data/EXT4_LAGFIX.log
fi;

fi