#!/system/bin/sh
### FeraDroid Engine v1.1 | By FeraVolt. 2017 ###
B=busybox;
MAX=$($B cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq);
MIN=$($B cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq);
CMAX=$($B cat /sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_max_freq);
CMIN=$($B cat /sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_min_freq);
CUR=$($B cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq);
CORES=$($B grep -c 'processor' /proc/cpuinfo);
FDE="$(busybox cat /data/CrossBreeder/FDE/ENABLE)"

if [ "$FDE" = "1" ]; then

if [ "$CORES" = "0" ]; then
 CORES=1;
fi;
$B echo "Current CPU freq: $((CUR/1000))Mhz" >> /data/cb_CHECK_PROCS.log
if [ -e /sys/module/msm_thermal/core_control/enabled ]; then
 $B echo "Disabing MSM thermal core for now.." >> /data/cb_CHECK_PROCS.log
 $B echo "0" > /sys/module/msm_thermal/core_control/enabled;
fi;
if [ -e /system/bin/mpdecision ]; then
 $B echo "Stop mpdecision for now.." >> /data/cb_CHECK_PROCS.log
 stop mpdecision;
fi;
if [ -e /system/bin/thermald ]; then
 $B echo "Stop thermald." >> /data/cb_CHECK_PROCS.log
 setprop ctl.stop thermald;
 stop thermald;
fi;
for mm in /sys/devices/soc.*/qcom,bcl.*; do
 $B echo -n "disable" > "${mm}"/mode;
done;
if [ -e /sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_min_freq ]; then
 if [ "$CMIN" != "$MIN" ]; then
  $B echo "Underclocking your CPU to $((CMIN/1000))Mhz.." >> /data/cb_CHECK_PROCS.log
  for a in 0 1 2 3 4 5 6 7; do
   $B echo "$CMIN" > /sys/devices/system/cpu/cpu$a/cpufreq/scaling_min_freq;
  done;
 fi;
fi;
if [ -e /sys/devices/system/cpu/cpufreq/ondemand/io_is_busy ]; then
 $B echo "CPU ondemand tuning.." >> /data/cb_CHECK_PROCS.log
 $B echo "10000" > /sys/devices/system/cpu/cpufreq/ondemand/sampling_rate;
 $B echo "1" > /sys/devices/system/cpu/cpufreq/ondemand/io_is_busy;
 $B echo "2" > /sys/devices/system/cpu/cpufreq/ondemand/sampling_down_factor;
 if [ -e /sys/devices/system/cpu/cpufreq/ondemand/powersave_bias ]; then
  $B echo "0" > /sys/devices/system/cpu/cpufreq/ondemand/powersave_bias;
 fi;
fi;
if [ -e /sys/devices/system/cpu/cpu0/cpufreq/ondemand/io_is_busy ]; then
 $B echo "CPU LITTLE cluster ondemand tuning.." >> /data/cb_CHECK_PROCS.log
 for fg in 0 1 2 3; do
  $B echo "10000" > /sys/devices/system/cpu/cpu$fg/cpufreq/ondemand/sampling_rate;
  $B echo "2" > /sys/devices/system/cpu/cpu$fg/cpufreq/ondemand/sampling_down_factor;
  $B echo "1" > /sys/devices/system/cpu/cpu$fg/cpufreq/ondemand/io_is_busy;
  if [ -e /sys/devices/system/cpu/cpu0/cpufreq/ondemand/powersave_bias ]; then
   if [ "$MAX" -gt "2000000" ]; then
    $B echo "100" > /sys/devices/system/cpu/cpu$fg/cpufreq/ondemand/powersave_bias;
   else
    $B echo "0" > /sys/devices/system/cpu/cpu$fg/cpufreq/ondemand/powersave_bias;
   fi;
  fi;
 done;
fi;
if [ -e /sys/devices/system/cpu/cpu4/cpufreq/ondemand/io_is_busy ]; then
 $B echo "CPU big cluster ondemand tuning.." >> /data/cb_CHECK_PROCS.log
 for c in 4 5 6 7; do
  $B echo "10000" > /sys/devices/system/cpu/cpu$c/cpufreq/ondemand/sampling_rate;
  $B echo "2" > /sys/devices/system/cpu/cpu$c/cpufreq/ondemand/sampling_down_factor;
  $B echo "1" > /sys/devices/system/cpu/cpu$c/cpufreq/ondemand/io_is_busy;
  if [ -e /sys/devices/system/cpu/cpu4/cpufreq/ondemand/powersave_bias ]; then
   if [ "$MAX" -gt "2000000" ]; then
    $B echo "100" > /sys/devices/system/cpu/cpu$c/cpufreq/ondemand/powersave_bias;
   else
    $B echo "0" > /sys/devices/system/cpu/cpu$c/cpufreq/ondemand/powersave_bias;
   fi;
  fi;
 done;
fi;
if [ -e /sys/devices/system/cpu/cpufreq/ondemandx/io_is_busy ]; then
 $B echo "CPU ondemandx tuning.." >> /data/cb_CHECK_PROCS.log
 $B echo "10000" > /sys/devices/system/cpu/cpufreq/ondemandx/sampling_rate;
 $B echo "1" > /sys/devices/system/cpu/cpufreq/ondemandx/io_is_busy;
 $B echo "2" > /sys/devices/system/cpu/cpufreq/ondemandx/sampling_down_factor;
 if [ -e /sys/devices/system/cpu/cpufreq/ondemandx/powersave_bias ]; then
  $B echo "0" > /sys/devices/system/cpu/cpufreq/ondemandx/powersave_bias;
 fi
fi;
if [ -e /sys/devices/system/cpu/cpu0/cpufreq/ondemandx/io_is_busy ]; then
 $B echo "CPU LITTLE cluster ondemandx tuning.." >> /data/cb_CHECK_PROCS.log
 for d in 0 1 2 3; do
  $B echo "10000" > /sys/devices/system/cpu/cpu$d/cpufreq/ondemandx/sampling_rate;
  $B echo "2" > /sys/devices/system/cpu/cpu$d/cpufreq/ondemandx/sampling_down_factor;
  $B echo "1" > /sys/devices/system/cpu/cpu$d/cpufreq/ondemandx/io_is_busy;
  if [ -e /sys/devices/system/cpu/cpu0/cpufreq/ondemandx/powersave_bias ]; then
   if [ "$MAX" -gt "2000000" ]; then
    $B echo "100" > /sys/devices/system/cpu/cpu$d/cpufreq/ondemandx/powersave_bias;
   else
    $B echo "0" > /sys/devices/system/cpu/cpu$d/cpufreq/ondemandx/powersave_bias;
   fi;
  fi;
 done;
fi;
if [ -e /sys/devices/system/cpu/cpu4/cpufreq/ondemandx/io_is_busy ]; then
 $B echo "CPU big cluster ondemandx tuning.." >> /data/cb_CHECK_PROCS.log
 for e in 4 5 6 7; do
  $B echo "10000" > /sys/devices/system/cpu/cpu$e/cpufreq/ondemandx/sampling_rate;
  $B echo "2" > /sys/devices/system/cpu/cpu$e/cpufreq/ondemandx/sampling_down_factor;
  $B echo "1" > /sys/devices/system/cpu/cpu$e/cpufreq/ondemandx/io_is_busy;
  if [ -e /sys/devices/system/cpu/cpu4/cpufreq/ondemandx/powersave_bias ]; then
   if [ "$MAX" -gt "2000000" ]; then
    $B echo "100" > /sys/devices/system/cpu/cpu$e/cpufreq/ondemandx/powersave_bias;
   else
    $B echo "0" > /sys/devices/system/cpu/cpu$e/cpufreq/ondemandx/powersave_bias;
   fi;
  fi;
 done;
fi;
if [ -e /sys/devices/system/cpu/cpufreq/sprdemand/io_is_busy ]; then
 $B echo "CPU sprdemand tuning.." >> /data/cb_CHECK_PROCS.log
 $B echo "10000" > /sys/devices/system/cpu/cpufreq/sprdemand/sampling_rate;
 $B echo "1" > /sys/devices/system/cpu/cpufreq/sprdemand/io_is_busy;
 $B echo "3" > /sys/devices/system/cpu/cpufreq/sprdemand/sampling_down_factor;
 if [ -e /sys/devices/system/cpu/cpufreq/sprdemand/powersave_bias ]; then
  $B echo "0" > /sys/devices/system/cpu/cpufreq/sprdemand/powersave_bias;
 fi;
fi;
if [ -e /sys/devices/system/cpu/cpu0/cpufreq/sprdemand/io_is_busy ]; then
 $B echo "CPU LITTLE cluster sprdemand tuning.." >> /data/cb_CHECK_PROCS.log
 for f in 0 1 2 3; do
  $B echo "10000" > /sys/devices/system/cpu/cpu$f/cpufreq/sprdemand/sampling_rate;
  $B echo "3" > /sys/devices/system/cpu/cpu$f/cpufreq/sprdemand/sampling_down_factor;
  $B echo "1" > /sys/devices/system/cpu/cpu$f/cpufreq/sprdemand/io_is_busy;
  if [ -e /sys/devices/system/cpu/cpu0/cpufreq/sprdemand/powersave_bias ]; then
   $B echo "0" > /sys/devices/system/cpu/cpu$f/cpufreq/sprdemand/powersave_bias;
  fi;
 done;
fi;
if [ -e /sys/devices/system/cpu/cpufreq/smartass/up_rate_us ]; then
 $B echo "CPU smartass tuning.." >> /data/cb_CHECK_PROCS.log
 $B echo "0" > /sys/devices/system/cpu/cpufreq/smartass/debug_mask;
 $B echo "192000" > /sys/devices/system/cpu/cpufreq/smartass/ramp_up_step;
 $B echo "192000" > /sys/devices/system/cpu/cpufreq/smartass/ramp_down_step;
 $B echo "10000" > /sys/devices/system/cpu/cpufreq/smartass/up_rate_us;
 $B echo "10000" > /sys/devices/system/cpu/cpufreq/smartass/down_rate_us;
 $B echo "2" > /sys/devices/system/cpu/cpufreq/smartass/sample_rate_jiffies;
fi;
if [ -e /sys/devices/system/cpu/cpu0/cpufreq/smartass/up_rate_us ]; then
 $B echo "CPU LITTLE cluster smartass tuning.." >> /data/cb_CHECK_PROCS.log
 for g in 0 1 2 3; do
  $B echo "0" > /sys/devices/system/cpu/cpu$g/cpufreq/smartass/debug_mask;
  $B echo "192000" > /sys/devices/system/cpu/cpu$g/cpufreq/smartass/ramp_up_step;
  $B echo "192000" > /sys/devices/system/cpu/cpu$g/cpufreq/smartass/ramp_down_step;
  $B echo "10000" > /sys/devices/system/cpu/cpu$g/cpufreq/smartass/up_rate_us;
  $B echo "10000" > /sys/devices/system/cpu/cpu$g/cpufreq/smartass/down_rate_us;
  $B echo "2" > /sys/devices/system/cpu/cpu$g/cpufreq/smartass/sample_rate_jiffies;
 done;
fi;
if [ -e /sys/devices/system/cpu/cpu4/cpufreq/smartass/up_rate_us ]; then
 $B echo "CPU big cluster smartass tuning.." >> /data/cb_CHECK_PROCS.log
 for h in 4 5 6 7; do
  $B echo "0" > /sys/devices/system/cpu/cpu$h/cpufreq/smartass/debug_mask;
  $B echo "192000" > /sys/devices/system/cpu/cpu$h/cpufreq/smartass/ramp_up_step;
  $B echo "192000" > /sys/devices/system/cpu/cpu$h/cpufreq/smartass/ramp_down_step;
  $B echo "10000" > /sys/devices/system/cpu/cpu$h/cpufreq/smartass/up_rate_us;
  $B echo "10000" > /sys/devices/system/cpu/cpu$h/cpufreq/smartass/down_rate_us;
  $B echo "2" > /sys/devices/system/cpu/cpu$h/cpufreq/smartass/sample_rate_jiffies;
 done;
fi;
if [ -e /sys/devices/system/cpu/cpufreq/smartassV2/up_rate_us ]; then
 $B echo "CPU smartassV2 tuning.." >> /data/cb_CHECK_PROCS.log
 $B echo "0" > /sys/devices/system/cpu/cpufreq/smartassV2/debug_mask;
 $B echo "192000" > /sys/devices/system/cpu/cpufreq/smartassV2/ramp_up_step;
 $B echo "192000" > /sys/devices/system/cpu/cpufreq/smartassV2/ramp_down_step;
 $B echo "10000" > /sys/devices/system/cpu/cpufreq/smartassV2/up_rate_us;
 $B echo "10000" > /sys/devices/system/cpu/cpufreq/smartassV2/down_rate_us;
 $B echo "2" > /sys/devices/system/cpu/cpufreq/smartassV2/sample_rate_jiffies;
fi;
if [ -e /sys/devices/system/cpu/cpu0/cpufreq/smartassV2/up_rate_us ]; then
 $B echo "CPU LITTLE cluster smartassV2 tuning.." >> /data/cb_CHECK_PROCS.log
 for j in 0 1 2 3; do
  $B echo "0" > /sys/devices/system/cpu/cpu$j/cpufreq/smartassV2/debug_mask;
  $B echo "192000" > /sys/devices/system/cpu/cpu$j/cpufreq/smartassV2/ramp_up_step;
  $B echo "192000" > /sys/devices/system/cpu/cpu$j/cpufreq/smartassV2/ramp_down_step;
  $B echo "10000" > /sys/devices/system/cpu/cpu$j/cpufreq/smartassV2/up_rate_us;
  $B echo "10000" > /sys/devices/system/cpu/cpu$j/cpufreq/smartassV2/down_rate_us;
  $B echo "2" > /sys/devices/system/cpu/cpu$j/cpufreq/smartassV2/sample_rate_jiffies;
 done;
fi;
if [ -e /sys/devices/system/cpu/cpu4/cpufreq/smartassV2/up_rate_us ]; then
 $B echo "CPU big cluster smartassV2 tuning.." >> /data/cb_CHECK_PROCS.log
 for k in 4 5 6 7; do
  $B echo "0" > /sys/devices/system/cpu/cpu$k/cpufreq/smartassV2/debug_mask;
  $B echo "192000" > /sys/devices/system/cpu/cpu$k/cpufreq/smartassV2/ramp_up_step;
  $B echo "192000" > /sys/devices/system/cpu/cpu$k/cpufreq/smartassV2/ramp_down_step;
  $B echo "10000" > /sys/devices/system/cpu/cpu$k/cpufreq/smartassV2/up_rate_us;
  $B echo "10000" > /sys/devices/system/cpu/cpu$k/cpufreq/smartassV2/down_rate_us;
  $B echo "2" > /sys/devices/system/cpu/cpu$k/cpufreq/smartassV2/sample_rate_jiffies;
 done;
fi;
if [ -e /sys/devices/system/cpu/cpufreq/smartassH3/up_rate_us ]; then
 $B echo "CPU smartassH3 tuning.." >> /data/cb_CHECK_PROCS.log
 $B echo "0" > /sys/devices/system/cpu/cpufreq/smartassH3/debug_mask;
 $B echo "192000" > /sys/devices/system/cpu/cpufreq/smartassH3/ramp_up_step;
 $B echo "192000" > /sys/devices/system/cpu/cpufreq/smartassH3/ramp_down_step;
 $B echo "10000" > /sys/devices/system/cpu/cpufreq/smartassH3/up_rate_us;
 $B echo "10000" > /sys/devices/system/cpu/cpufreq/smartassH3/down_rate_us;
 $B echo "69" > /sys/devices/system/cpu/cpufreq/smartassH3/max_cpu_load;
 $B echo "18" > /sys/devices/system/cpu/cpufreq/smartassH3/min_cpu_load;
 $B echo "2" > /sys/devices/system/cpu/cpufreq/smartassH3/sample_rate_jiffies;
 $B echo "0" > /sys/devices/system/cpu/cpufreq/smartassH3/boost_enabled;
fi;
if [ -e /sys/devices/system/cpu/cpu0/cpufreq/smartassH3/up_rate_us ]; then
 $B echo "CPU LITTLE cluster smartassH3 tuning.." >> /data/cb_CHECK_PROCS.log
 for l in 0 1 2 3; do
  $B echo "0" > /sys/devices/system/cpu/cpu$l/cpufreq/smartassH3/debug_mask;
  $B echo "192000" > /sys/devices/system/cpu/cpu$l/cpufreq/smartassH3/ramp_up_step;
  $B echo "192000" > /sys/devices/system/cpu/cpu$l/cpufreq/smartassH3/ramp_down_step;
  $B echo "10000" > /sys/devices/system/cpu/cpu$l/cpufreq/smartassH3/up_rate_us;
  $B echo "10000" > /sys/devices/system/cpu/cpu$l/cpufreq/smartassH3/down_rate_us;
  $B echo "69" > /sys/devices/system/cpu/cpu$l/cpufreq/smartassH3/max_cpu_load;
  $B echo "18" > /sys/devices/system/cpu/cpu$l/cpufreq/smartassH3/min_cpu_load;
  $B echo "2" > /sys/devices/system/cpu/cpu$l/cpufreq/smartassH3/sample_rate_jiffies;
  if [ -e /sys/devices/system/cpu/cpu0/cpufreq/smartassH3/boost_enabled ]; then
   $B echo "1" > /sys/devices/system/cpu/cpu$l/cpufreq/smartassH3/boost_enabled;
   $B echo "3000000" > /sys/devices/system/cpu/cpu$l/cpufreq/smartassH3/boost_pulse;
  fi;
 done;
fi;
if [ -e /sys/devices/system/cpu/cpu4/cpufreq/smartassH3/up_rate_us ]; then
 $B echo "CPU big cluster smartassH3 tuning.." >> /data/cb_CHECK_PROCS.log
 for m in 4 5 6 7; do
  $B echo "0" > /sys/devices/system/cpu/cpu$m/cpufreq/smartassH3/debug_mask;
  $B echo "192000" > /sys/devices/system/cpu/cpu$m/cpufreq/smartassH3/ramp_up_step;
  $B echo "192000" > /sys/devices/system/cpu/cpu$m/cpufreq/smartassH3/ramp_down_step;
  $B echo "10000" > /sys/devices/system/cpu/cpu$m/cpufreq/smartassH3/up_rate_us;
  $B echo "10000" > /sys/devices/system/cpu/cpu$m/cpufreq/smartassH3/down_rate_us;
  $B echo "69" > /sys/devices/system/cpu/cpu$m/cpufreq/smartassH3/max_cpu_load;
  $B echo "18" > /sys/devices/system/cpu/cpu$m/cpufreq/smartassH3/min_cpu_load;
  $B echo "2" > /sys/devices/system/cpu/cpu$m/cpufreq/smartassH3/sample_rate_jiffies;
  if [ -e /sys/devices/system/cpu/cpu4/cpufreq/smartassH3/boost_enabled ]; then
   $B echo "1" > /sys/devices/system/cpu/cpu$m/cpufreq/smartassH3/boost_enabled;
   $B echo "3000000" > /sys/devices/system/cpu/cpu$m/cpufreq/smartassH3/boost_pulse;
  fi;
 done;
fi;
if [ -e /sys/devices/system/cpu/cpufreq/interactive/min_sample_time ]; then
 $B echo "CPU interactive tuning.." >> /data/cb_CHECK_PROCS.log
 $B echo "1" > /sys/devices/system/cpu/cpufreq/interactive/io_is_busy;
 $B echo "0" > /sys/devices/system/cpu/cpufreq/interactive/use_sched_load;
 $B echo "1" > /sys/devices/system/cpu/cpufreq/interactive/use_migration_notif;
 $B echo "50000" > /sys/devices/system/cpu/cpufreq/interactive/min_sample_time;
fi;
if [ -e /sys/devices/system/cpu/cpu0/cpufreq/interactive/min_sample_time ]; then
 $B echo "CPU LITTLE cluster interactive tuning.." >> /data/cb_CHECK_PROCS.log
 for o in 0 1 2 3; do
  $B echo "1" > /sys/devices/system/cpu/cpu$o/cpufreq/interactive/io_is_busy;
  $B echo "0" > /sys/devices/system/cpu/cpu$o/cpufreq/interactive/use_sched_load;
  $B echo "1" > /sys/devices/system/cpu/cpu$o/cpufreq/interactive/use_migration_notif;
  $B echo "50000" > /sys/devices/system/cpu/cpu$o/cpufreq/interactive/min_sample_time;
 done;
fi;
if [ -e /sys/devices/system/cpu/cpu4/cpufreq/interactive/min_sample_time ]; then
 $B echo "CPU big cluster interactive tuning.." >> /data/cb_CHECK_PROCS.log
 for p in 4 5 6 7; do
  $B echo "1" > /sys/devices/system/cpu/cpu$p/cpufreq/interactive/io_is_busy;
  $B echo "0" > /sys/devices/system/cpu/cpu$p/cpufreq/interactive/use_sched_load;
  $B echo "1" > /sys/devices/system/cpu/cpu$p/cpufreq/interactive/use_migration_notif;
  $B echo "50000" > /sys/devices/system/cpu/cpu$p/cpufreq/interactive/min_sample_time;
 done;
fi;
if [ -e /sys/devices/system/cpu/cpufreq/interactivex/min_sample_time ]; then
 $B echo "CPU interactivex tuning.." >> /data/cb_CHECK_PROCS.log
 $B echo "1" > /sys/devices/system/cpu/cpufreq/interactivex/io_is_busy;
 $B echo "0" > /sys/devices/system/cpu/cpufreq/interactivex/use_sched_load;
 $B echo "1" > /sys/devices/system/cpu/cpufreq/interactivex/use_migration_notif;
 $B echo "50000" > /sys/devices/system/cpu/cpufreq/interactivex/min_sample_time;
fi;
if [ -e /sys/devices/system/cpu/cpu0/cpufreq/interactivex/min_sample_time ]; then
 $B echo "CPU LITTLE cluster interactivex tuning.." >> /data/cb_CHECK_PROCS.log
 for q in 0 1 2 3; do
  $B echo "1" > /sys/devices/system/cpu/cpu$q/cpufreq/interactivex/io_is_busy;
  $B echo "0" > /sys/devices/system/cpu/cpu$q/cpufreq/interactivex/use_sched_load;
  $B echo "1" > /sys/devices/system/cpu/cpu$q/cpufreq/interactivex/use_migration_notif;
  $B echo "50000" > /sys/devices/system/cpu/cpu$q/cpufreq/interactivex/min_sample_time;
 done;
fi;
if [ -e /sys/devices/system/cpu/cpu4/cpufreq/interactivex/min_sample_time ]; then
 $B echo "CPU big cluster interactivex tuning.." >> /data/cb_CHECK_PROCS.log
 for r in 4 5 6 7; do
  $B echo "1" > /sys/devices/system/cpu/cpu$r/cpufreq/interactivex/io_is_busy;
  $B echo "0" > /sys/devices/system/cpu/cpu$r/cpufreq/interactivex/use_sched_load;
  $B echo "1" > /sys/devices/system/cpu/cpu$r/cpufreq/interactivex/use_migration_notif;
  $B echo "50000" > /sys/devices/system/cpu/cpu$r/cpufreq/interactivex/min_sample_time;
 done;
fi;
if [ -e /sys/devices/system/cpu/cpufreq/interactiveplus/min_sample_time ]; then
 $B echo "CPU interactiveplus tuning.." >> /data/cb_CHECK_PROCS.log
 $B echo "1" > /sys/devices/system/cpu/cpufreq/interactiveplus/io_is_busy;
 $B echo "0" > /sys/devices/system/cpu/cpufreq/interactiveplus/use_sched_load;
 $B echo "1" > /sys/devices/system/cpu/cpufreq/interactiveplus/use_migration_notif;
 $B echo "50000" > /sys/devices/system/cpu/cpufreq/interactiveplus/min_sample_time;
fi;
if [ -e /sys/devices/system/cpu/cpu0/cpufreq/interactiveplus/min_sample_time ]; then
 $B echo "CPU LITTLE cluster interactiveplus tuning.." >> /data/cb_CHECK_PROCS.log
 for q in 0 1 2 3; do
  $B echo "1" > /sys/devices/system/cpu/cpu$q/cpufreq/interactiveplus/io_is_busy;
  $B echo "0" > /sys/devices/system/cpu/cpu$q/cpufreq/interactiveplus/use_sched_load;
  $B echo "1" > /sys/devices/system/cpu/cpu$q/cpufreq/interactiveplus/use_migration_notif;
  $B echo "50000" > /sys/devices/system/cpu/cpu$q/cpufreq/interactiveplus/min_sample_time;
 done;
fi;
if [ -e /sys/devices/system/cpu/cpu4/cpufreq/interactiveplus/min_sample_time ]; then
 $B echo "CPU big cluster interactiveplus tuning.." >> /data/cb_CHECK_PROCS.log
 for r in 4 5 6 7; do
  $B echo "1" > /sys/devices/system/cpu/cpu$r/cpufreq/interactiveplus/io_is_busy;
  $B echo "0" > /sys/devices/system/cpu/cpu$r/cpufreq/interactiveplus/use_sched_load;
  $B echo "1" > /sys/devices/system/cpu/cpu$r/cpufreq/interactiveplus/use_migration_notif;
  $B echo "50000" > /sys/devices/system/cpu/cpu$r/cpufreq/interactiveplus/min_sample_time;
 done;
fi;
if [ -e /sys/devices/system/cpu/cpufreq/pegasusq/io_is_busy ]; then
 $B echo "CPU pegasusq tuning.. >> /data/cb_CHECK_PROCS.log"
 $B echo "1" > /sys/devices/system/cpu/cpufreq/pegasusq/io_is_busy;
 $B echo "3" > /sys/devices/system/cpu/cpufreq/pegasusq/sampling_down_factor;
 $B echo "10000" > /sys/devices/system/cpu/cpufreq/pegasusq/sampling_rate;
fi;
if [ -e /sys/devices/system/cpu/cpu0/cpufreq/pegasusq/io_is_busy ]; then
 $B echo "CPU LITTLE cluster pegasusq tuning.." >> /data/cb_CHECK_PROCS.log
 for s in 0 1 2 3; do
  $B echo "1" > /sys/devices/system/cpu/cpu$s/cpufreq/pegasusq/io_is_busy;
  $B echo "3" > /sys/devices/system/cpu/cpu$s/cpufreq/pegasusq/sampling_down_factor;
  $B echo "10000" > /sys/devices/system/cpu/cpu$s/cpufreq/pegasusq/sampling_rate;
 done;
fi;
if [ -e /sys/devices/system/cpu/cpu4/cpufreq/pegasusq/io_is_busy ]; then
 $B echo "CPU big cluster pegasusq tuning.." >> /data/cb_CHECK_PROCS.log
 for t in 4 5 6 7; do
  $B echo "1" > /sys/devices/system/cpu/cpu$t/cpufreq/pegasusq/io_is_busy;
  $B echo "3" > /sys/devices/system/cpu/cpu$t/cpufreq/pegasusq/sampling_down_factor;
  $B echo "10000" > /sys/devices/system/cpu/cpu$t/cpufreq/pegasusq/sampling_rate;
 done;
fi;
if [ -e /sys/devices/system/cpu/cpufreq/lulzactive/inc_cpu_load ]; then
 $B echo "CPU lulzactive tuning.." >> /data/cb_CHECK_PROCS.log
 $B echo "85" > /sys/devices/system/cpu/cpufreq/lulzactive/inc_cpu_load;
fi;
if [ -e /sys/devices/system/cpu/cpu0/cpufreq/lulzactive/inc_cpu_load ]; then
 $B echo "CPU LITTLE cluster lulzactive tuning.." >> /data/cb_CHECK_PROCS.log
 for u in 0 1 2 3; do
  $B echo "85" > /sys/devices/system/cpu/cpu$u/cpufreq/lulzactive/inc_cpu_load;
 done;
fi;
if [ -e /sys/devices/system/cpu/cpu4/cpufreq/lulzactive/inc_cpu_load ]; then
 $B echo "CPU big cluster lulzactive tuning.." >> /data/cb_CHECK_PROCS.log
 for v in 4 5 6 7; do
  $B echo "85" > /sys/devices/system/cpu/cpu$v/cpufreq/lulzactive/inc_cpu_load;
 done;
fi;
if [ -e /sys/devices/system/cpu/cpufreq/conservative/sampling_rate ]; then
 $B echo "CPU conservative tuning.." >> /data/cb_CHECK_PROCS.log
 $B echo "70000" > /sys/devices/system/cpu/cpufreq/conservative/sampling_rate;
 $B echo "10" > /sys/devices/system/cpu/cpufreq/conservative/freq_step;
 $B echo "69" > /sys/devices/system/cpu/cpufreq/conservative/up_threshold;
 $B echo "18" > /sys/devices/system/cpu/cpufreq/conservative/down_threshold;
 $B echo "6" > /sys/devices/system/cpu/cpufreq/conservative/sampling_down_factor;
fi;
if [ -e /sys/devices/system/cpu/cpu0/cpufreq/conservative/sampling_rate ]; then
 $B echo "CPU LITTLE cluster conservative tuning.." >> /data/cb_CHECK_PROCS.log
 for w in 0 1 2 3; do
  $B echo "70000" > /sys/devices/system/cpu/cpu$w/cpufreq/conservative/sampling_rate;
  $B echo "10" > /sys/devices/system/cpu/cpu$w/cpufreq/conservative/freq_step;
  $B echo "69" > /sys/devices/system/cpu/cpu$w/cpufreq/conservative/up_threshold;
  $B echo "18" > /sys/devices/system/cpu/cpu$w/cpufreq/conservative/down_threshold;
  $B echo "6" > /sys/devices/system/cpu/cpu$w/cpufreq/conservative/sampling_down_factor;
 done;
fi;
if [ -e /sys/devices/system/cpu/cpu4/cpufreq/conservative/sampling_rate ]; then
 $B echo "CPU big cluster conservative tuning.." >> /data/cb_CHECK_PROCS.log
 for x in 4 5 6 7; do
  $B echo "10000" > /sys/devices/system/cpu/cpu$x/cpufreq/conservative/sampling_rate;
  $B echo "25" > /sys/devices/system/cpu/cpu$x/cpufreq/conservative/freq_step;
 done;
fi;
if [ -e /sys/devices/system/cpu/cpufreq/intellidemand/sampling_rate ]; then
 $B echo "CPU intellidemand tuning.." >> /data/cb_CHECK_PROCS.log
 $B echo "10000" > /sys/devices/system/cpu/cpufreq/intellidemand/sampling_rate;
fi;
if [ -e /sys/devices/system/cpu/cpu0/cpufreq/intellidemand/sampling_rate ]; then
 $B echo "CPU LITTLE cluster intellidemand tuning.." >> /data/cb_CHECK_PROCS.log
 for y in 0 1 2 3; do
  $B echo "10000" > /sys/devices/system/cpu/cpu$y/cpufreq/intellidemand/sampling_rate;
 done;
fi;
if [ -e /sys/devices/system/cpu/cpu4/cpufreq/intellidemand/sampling_rate ]; then
 $B echo "CPU big cluster intellidemand tuning.." >> /data/cb_CHECK_PROCS.log
 for z in 4 5 6 7; do
  $B echo "10000" > /sys/devices/system/cpu/cpu$z/cpufreq/intellidemand/sampling_rate;
 done;
fi;
if [ -e /sys/devices/system/cpu/cpufreq/neox/freq_step ]; then
 $B echo "CPU neox tuning.." >> /data/cb_CHECK_PROCS.log
 $B echo "100" > /sys/devices/system/cpu/cpufreq/neox/freq_step;
fi;
if [ -e /sys/devices/system/cpu/cpu0/cpufreq/neox/freq_step ]; then
 $B echo "CPU LITTLE cluster neox tuning.." >> /data/cb_CHECK_PROCS.log
 for ab in 0 1 2 3; do
  $B echo "100" > /sys/devices/system/cpu/cpu$ab/cpufreq/neox/freq_step;
 done;
fi;
if [ -e /sys/devices/system/cpu/cpu4/cpufreq/neox/freq_step ]; then
 $B echo "CPU big cluster neox tuning.." >> /data/cb_CHECK_PROCS.log
 for bc in 4 5 6 7; do
  $B echo "100" > /sys/devices/system/cpu/cpu$bc/cpufreq/neox/freq_step;
 done;
fi;
if [ -e /sys/devices/system/cpu/cpufreq/hotplug/io_is_busy ]; then
 $B echo "CPU hotplug tuning.." >> /data/cb_CHECK_PROCS.log
 $B echo "1" > /sys/devices/system/cpu/cpufreq/hotplug/io_is_busy;
 $B echo "10000" > /sys/devices/system/cpu/cpufreq/hotplug/sampling_rate;
fi;
if [ -e /sys/devices/system/cpu/cpu0/cpufreq/hotplug/io_is_busy ]; then
 $B echo "CPU LITTLE cluster hotplug tuning.." >> /data/cb_CHECK_PROCS.log
 for de in 0 1 2 3; do
  $B echo "1" > /sys/devices/system/cpu/cpu$de/cpufreq/hotplug/io_is_busy;
  $B echo "10000" > /sys/devices/system/cpu/cpu$de/cpufreq/hotplug/sampling_rate;
 done;
fi;
if [ -e /sys/devices/system/cpu/cpu4/cpufreq/hotplug/io_is_busy ]; then
 $B echo "CPU big cluster hotplug tuning.." >> /data/cb_CHECK_PROCS.log
 for ef in 4 5 6 7; do
  $B echo "1" > /sys/devices/system/cpu/cpu$ef/cpufreq/hotplug/io_is_busy;
  $B echo "10000" > /sys/devices/system/cpu/cpu$ef/cpufreq/hotplug/sampling_rate;
 done;
fi;
if [ -e /sys/module/workqueue/parameters/power_efficient ]; then
 $B echo "Enabling power-save workqueues.." >> /data/cb_CHECK_PROCS.log
 $B echo "1" > /sys/module/workqueue/parameters/power_efficient;
 $B echo "Y" > /sys/module/workqueue/parameters/power_efficient;
fi;
if [ -e /sys/module/subsystem_restart/parameters/enable_ramdumps ]; then
 $B echo "Disabling RAM-dumps.." >> /data/cb_CHECK_PROCS.log
 $B echo "0" > /sys/module/subsystem_restart/parameters/enable_ramdumps;
fi;
if [ -e /sys/module/cpuidle/parameters/enable_mask ]; then
 $B echo "Enabling AFTR + LPA.." >> /data/cb_CHECK_PROCS.log
 $B echo "3" > /sys/module/cpuidle/parameters/enable_mask;
fi;
if [ -e /sys/devices/system/cpu/cpu0/cpufreq/busfreq_static ]; then
 $B echo "Disabling static bus-freq.." >> /data/cb_CHECK_PROCS.log
 $B echo "disabled" > /sys/devices/system/cpu/cpu0/cpufreq/busfreq_static;
fi;
if [ -e /sys/devices/system/cpu/sched_mc_power_savings ]; then
 $B echo "Enabling Multi-core power-saving.." >> /data/cb_CHECK_PROCS.log
 $B echo "2" > /sys/devices/system/cpu/sched_mc_power_savings;
fi;
if [ -e /proc/sys/abi/swp ]; then
 $B echo "Activating ARM8 SWP.." >> /data/cb_CHECK_PROCS.log
 $B echo "1" > /proc/sys/abi/swp;
fi;
if [ "$CORES" -le "4" ]; then
 if [ -e /sys/module/pm_hotplug/parameters/loadh ]; then
  $B echo "Tuning Dual-Core behavior.." >> /data/cb_CHECK_PROCS.log
  $B echo "85" > /sys/module/pm_hotplug/parameters/loadh;
  $B echo "18" > /sys/module/pm_hotplug/parameters/loadl;
 fi;
 if [ -e /sys/devices/virtual/misc/second_core/hotplug_on ]; then
  $B echo "Activating dynamic hot-plug.." >> /data/cb_CHECK_PROCS.log
  $B echo "on" > /sys/devices/virtual/misc/second_core/hotplug_on;
 fi;
 if [ -e /sys/devices/system/cpu/cpu0/cpufreq/smooth_target ]; then
  $B echo "Activating CPU smooth-target.." >> /data/cb_CHECK_PROCS.log
  $B echo "2" > /sys/devices/system/cpu/cpu0/cpufreq/smooth_target;
  $B echo "2" > /sys/devices/system/cpu/cpu0/cpufreq/smooth_offset;
  $B echo "2" > /sys/devices/system/cpu/cpu0/cpufreq/smooth_step;
 fi;
fi;
if [ -e /sys/module/msm_thermal/core_control/enabled ]; then
 $B echo "Enabling MSM thermal core & tuning it.." >> /data/cb_CHECK_PROCS.log
 $B echo "1" > /sys/module/msm_thermal/core_control/enabled;
 $B echo "N" > /sys/module/msm_thermal/parameters/enabled;
fi;
if [ -e /sys/devices/system/cpu/cpu0/core_ctl/busy_down_thres ]; then
 $B echo "Core-control LITTLE cluster scheduling tune-up.." >> /data/cb_CHECK_PROCS.log
 $B echo "40" > /sys/devices/system/cpu/cpu0/core_ctl/busy_down_thres;
 $B echo "65" > /sys/devices/system/cpu/cpu0/core_ctl/busy_up_thres;
 $B echo "100" > /sys/devices/system/cpu/cpu0/core_ctl/offline_delay_ms;
fi;
if [ -e /sys/devices/system/cpu/cpu4/core_ctl/busy_down_thres ]; then
 $B echo "Core-control big cluster scheduling tune-up.." >> /data/cb_CHECK_PROCS.log
 $B echo "45" > /sys/devices/system/cpu/cpu4/core_ctl/busy_down_thres;
 $B echo "72" > /sys/devices/system/cpu/cpu4/core_ctl/busy_up_thres;
 $B echo "0" > /sys/devices/system/cpu/cpu4/core_ctl/offline_delay_ms;
fi;
if [ -e /sys/module/cpu_boost/parameters/wakeup_boost ]; then
 $B echo "Wakeup boost..." >> /data/cb_CHECK_PROCS.log
 $B echo "1" > /sys/module/cpu_boost/parameters/wakeup_boost;
fi;
if [ -e /dev/cpuctl/bg_non_interactive/cpu.shares ]; then
 $B echo "192" > /dev/cpuctl/bg_non_interactive/cpu.shares
 $B echo "CPU background tune-up.." >> /data/cb_CHECK_PROCS.log
fi;
if [ -e /system/bin/mpdecision ]; then
 $B echo "Start mpdecision for now.." >> /data/cb_CHECK_PROCS.log
 start mpdecision;
fi;
sync;
$B sleep 1;

fi