#!/system/bin/sh

#calculate values
busybox echo "Setting optimal values of VM heap sizes."
RAM=$((` busybox awk '/MemTotal/{print $2}' /proc/meminfo` / 1024 ))

if [ "$RAM" -lt "512" ]
then
 THRESHOLD="450"
 setprop dalvik.vm.heaptargetutilization 0.9
else
 THRESHOLD="375"
 setprop dalvik.vm.heaptargetutilization 0.75
fi

HEAPMAXSIZE="$(( ($RAM * 268554 / 1000000) ))"
VMHEAP="$(( $HEAPMAXSIZE / ( 1000/$THRESHOLD ) ))"

#set vm parameters
busybox echo "Detected you have $RAM of system RAM."
busybox echo "==> Max heap: ${HEAPMAXSIZE}m"
busybox echo "==> Min heap: ${VMHEAP}m"

setprop dalvik.vm.heapsize "${HEAPMAXSIZE}m"
setprop dalvik.vm.heapgrowthlimit "${VMHEAP}m"
setprop persist.sys.vm.heapsize "${VMHEAP}m"
