#!/system/bin/sh

export PATH=/system/etc/CrossBreeder:/system/bin:/system/xbin:/sbin:/vendor/bin:/system/sbin

alias [='busybox ['
alias [[='busybox [['

GOOGLEDNS="$(busybox cat /data/CrossBreeder/zzCheck_Net_DNS/GOOGLEDNS)"
DNSMASQ="$(busybox cat /data/CrossBreeder/zzCheck_Net_DNS/DNSMASQ)"

set +e

if [ "$GOOGLEDNS" = "1" ]; then

iptables -t nat -I OUTPUT -p tcp --dport 53 -j DNAT --to-destination 8.8.8.8:53
iptables -t nat -I OUTPUT -p udp --dport 53 -j DNAT --to-destination 8.8.8.8:53

setprop net.dns1 8.8.8.8
setprop net.dns2 8.8.4.4
setprop net.rmnet0.dns1 8.8.8.8
setprop net.rmnet0.dns2 8.8.4.4
setprop net.gprs.dns1 8.8.8.8
setprop net.gprs.dns2 8.8.4.4
setprop net.ppp0.dns1 8.8.8.8
setprop net.ppp0.dns2 8.8.4.4
setprop net.wlan0.dns1 8.8.8.8
setprop net.wlan0.dns2 8.8.4.4
setprop net.eth0.dns1 8.8.8.8
setprop net.eth0.dns2 8.8.4.4

fi

if [ "$DNSMASQ" = "1" ]; then

ANDROID_DNS_MODE= dnsmasq --all-servers=/bit/178.63.16.21,/bit/95.211.195.245,/bit/178.32.31.41 2>/dev/null
pid=$!
busybox renice +20 $pid 2>/dev/null

fi
